sudo: false

language: go

go:
  - 1.9.x
  - 1.x

# Only clone the most recent commit.
git:
  depth: 1

install: true

# Don't email me the results of the test runs.
notifications:
  email: false

before_script:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure

script:
  - go test -v -race -cover -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
